### ISSUE TITLE
Handle default parameters in node client

### ISSUE THREAD

**Issue by Mossaka** [Mossaka/client-node#3]
Current implementation does not handle default parameters such as `cf`. 

If we do 
```javascript
client.get("k4") 
```

nodejs will return a unhelpful error message:
```sh
UnhandledPromiseRejectionWarning: TypeError: failed to downcast any to string
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at Object.<anonymous> (internal/util.js:296:12)
    at RawClient.get (/home/mossaka/developer/LFX/client-node/index.js:20:26)
    at /home/mossaka/developer/LFX/client-node/app.js:18:18
(node:24468) UnhandledPromiseRejectionWarning:
```
See more about Js default parameters: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

See more about how **Neon** handles default/optional arguments: https://neon-bindings.com/docs/arguments

**Comment by Mossaka** [comment]
I have an experiment implementation of the default parameters in `snapshot::scan`

```rust
let start = cx.argument_opt(0).map(|start| {
            start
                .downcast::<JsString, _>(&mut cx)
                .or_throw(&mut cx)
                .unwrap()
                .value(&mut cx)
                .into_bytes()
        });
let end = cx.argument_opt(1).map(|end| {
            end.downcast::<JsString, _>(&mut cx)
                .or_throw(&mut cx)
                .unwrap()
                .value(&mut cx)
                .into_bytes()
        });
```

This same method can be applied to other methods. There is a potential opportunity to extract the common logic out to `utils.rs`

**Comment by Mossaka** [comment]
It turns out that the above implementation handles the optional arguments when the length of the arguments is smaller than the required ones. A correct solution should expand on the handling of _downcasting_.

**Comment by Mossaka** [comment]
Another task:

`cf` in RawClient should be completely optional and we should provide a default value to it.
